name: CI

on:
    workflow_call:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    typecheckAndLint:
        name: Run typecheck and lint
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version-file: 'src/.nvmrc'
            - name: Get npm cache directory
              id: npm-cache-dir
              run: |
                echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              id: npm-cache
              with:
                path: ${{ steps.npm-cache-dir.outputs.dir }}
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Install packages
              run: npm ci
            - name: Run tsc in packages
              run: |
                for package in $(ls -d ./src/packages/*); do
                    tsc --build --noEmit "$package"
                done
                - name: Run tsc in packages
                run: |
                  for package in $(ls -d ./src/apps/*); do
                      tsc --build --noEmit "$package"
                  done
            - name: Run ESLint
              run: npx eslint --quiet .
