name: Deploy image cleanup worker to DEV

env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "src/apps/image-cleanup-worker/**"

jobs:
    buildAndDeploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version-file: 'src/.nvmrc'
            - name: Install packages
              run: npm ci
            - name: Run ESLint
              run: npx eslint --quiet .
            - name: Deploy worker
              run: npm run deploy -w @your-spot/image-cleanup-worker
