name: Deploy to Vercel Preview + Dev envs

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "src/**"

jobs:
    buildAndDeploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version-file: 'src/.nvmrc'
            - name: Install Vercel CLI
              run: npm install vercel@latest --global
            - name: Pull env variables
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy to Preview + assign Dev env
              run: |
                vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > preview-domain.txt
                vercel alias --scope ${{ secrets.VERCEL_TEAM_ID }} --token ${{ secrets.VERCEL_TOKEN }} set `cat preview-domain.txt` ${{ vars.DEV_DOMAIN }}
